{% set name = "sphinx_gmt" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6b468701d73a959a931cb85f7ff49b5a2d2ba97bb9e7807005c3f500c407521

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - jinja2
    - sphinx

test:
  imports:
    - sphinx_gmt.gmtplot

about:
  home: https://github.com/GenericMappingTools/sphinx_gmt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Sphinx extensions for the Generic Mapping Tools
  description: |
    This package provides a Sphinx extension for including GMT code and figures in your
    documentation.
  doc_url: https://www.generic-mapping-tools.org/sphinx_gmt
  dev_url: https://github.com/GenericMappingTools/sphinx_gmt

extra:
  recipe-maintainers:
    - leouieda
    - seisman
