travis:
  secure:
    BINSTAR_TOKEN: MC7A3k5gLCZ0tuB3EuaaYze+zvQSbhpm4UNOJtN63+P9sk9zqDIYDfjbZRViL9L8iEm0PHkIreV1h0fyB7ZoL4okOcIPKNsLRd8SybDAzwCCRsow4XIdLV5BYvyGhyT5xKYWnR9WWhY+6WqGbDPyT0unzikO8NOXk5NThMat80jPxdgtk9g+jTYoMeHNMQe7e+gBkQAsJKvmBl/dMJ0JiYW8sjHCZiPsZXoyCaQ34EbjYOrokIyC2ejqCqO1meGVZP0iQRK1WuoVdKUV4cm03BW/r4/dWKL1L1nwBKJ3pX1Zg2Uqj+BHcmhpl4KtCGosmgV+04DdEYaTJrHJnUzb8YTeIy+3XKYiinB/bVydR4IZXOSVhLSmpzUE/MHKxoN0i0L8z9VtmksxYz38kQQSgeMGa+VQct3tG+8AraLeSFeu2c8WxymPWhPBJOanyi+MM/0RKmevCqD7xv2sGfWRgj9ubQdEJAt4RsMNQIyNzoA6V51dV1hVQLZhcx2gs245+rKApZYRx2igonZ8RBfAT+VeXNJAC3uvRyiO+W+w9EUH2Dx0pKcZn//PaVJRrebPfqHUZXURe70zB+tsg8SGo1eofEhe5erfvLe4Nxmm9O+fO/v7prjI2Daou7lcuBkne94nVDKZA8jN5dh/xk4G0bMMflYF2WY/YQLZkUHZIZE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
